[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.11.0"

[context.production]
  command = "pnpm build"

[context.deploy-preview]
  command = "pnpm build"

[context.branch-deploy]
  command = "pnpm build"

[[headers]]
  for = "/api/*"
  [headers.values]
    cache-control = "no-store"
