[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.11.0"

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "public, max-age=0, must-revalidate"
